# On the comandline
# python tex2html/src/updatewebsitefiles.py

# Location of the online book files
onlineBookFolder: ../../leenamurgai.github.io

files:
  - index.html
  - MBML.pdf
  - README.md
  - tex2html/README.md
  - tex2html/tufte/tufte.css
  - tex2html/tufte/tufte.html5

chapters:
  - 01_MotivationAndContext
  - 02_EthicalDevelopment
  - 03_GroupFairness

figureFileTypes:
  - png
  - pdf
  - pdf_tex

tex2htmlFolderFileType:
  config: yml
  csl: csl
  css: css
  filters: lua
  src: py


