# On the comandline
# python tex2html/src/updatewebsitefiles.py

# Location of the online book files
onlineBookFolder: ../leenamurgai.github.io

files:
  - index.html
  - tex2html/README.md
  - tex2html/src/README.md
  - tex2html/tufte/tufte.css
  - tex2html/tufte/tufte.html5
  - profile/mbml_summary.md
  - profile/mbml_citation.bib

figFolders:
  - 01_Context
  - 02_EthicalDevelopment
  - 03_GroupFairness
  - 04_IndividualFairness
  - 05_InequalityIndices
  - profile
  - code

codeFileType: ipynb

figFileTypes:
  - png

tex2htmlFolderFileType:
  config: yml
  csl: csl
  css: css
  filters: lua
  src: py


